language: python
dist: xenial
# osx_image: xcode11
cache: pip

stages:
  - name: test
  - name: deploy
    if: tag IS present

# build matrix for test stage
python:
  - "3.6"
  - "3.7"
  - "3.8"
os:
  - linux
  # - osx  # Travis CI does not officially support Python on macOS.

matrix:
  fast_finish: true

# test stage
install:
  - pip install -U --upgrade-strategy=eager pip setuptools
  - pip install -U --upgrade-strategy=eager -e ".[dev,build,test]"
script:
  - python -m flake8 ai/backend tests
  - python -m mypy src/ai/backend
  - python -m pytest --cov=ai.backend.cli -v
after_success:
  - codecov

# other stages
jobs:
  include:
    - stage: deploy
      python: "3.8"
      install: skip
      script: skip
      deploy:
        on:
          tags: true
        provider: pypi
        distributions: sdist bdist_wheel
        skip_upload_docs: true
        user: "__token__"
        password:
          secure: "TODO"
