language: python
dist: xenial
# osx_image: xcode11
cache: pip

stages:
  - name: test
  - name: deploy
    if: tag IS present

# build matrix for test stage
python:
  - "3.6"
  - "3.7"
  - "3.8"
os:
  - linux
  # - osx  # Travis CI does not officially support Python on macOS.

matrix:
  fast_finish: true

# test stage
install:
  - pip install -U --upgrade-strategy=eager pip setuptools
  - pip install -U --upgrade-strategy=eager -e ".[dev,build,test]"
script:
  - python -m flake8 ai/backend tests
  - python -m mypy src/ai/backend
  - python -m pytest --cov=ai.backend.cli -v
after_success:
  - codecov

# other stages
jobs:
  include:
    - stage: deploy
      python: "3.8"
      install: skip
      script: skip
      deploy:
        on:
          tags: true
        provider: pypi
        distributions: sdist bdist_wheel
        skip_upload_docs: true
        user: "__token__"
        password:
          secure: "M+w0fwiaG/7FR7K27h5mTMt+r0VUEhQH9scALanur+Av14i4d02Bkfj7ToibKoLb2Li66kwci8bfSFHc163vtVTQQUN808fOLTaQFUEvJIlU4WtcVX6TOf/kaomq9VRVh39/gIn3XoBIY3M+OZD9z8haHQCMM38gdZwgkb6rooT0MlYTfITYaTHkul/rMw4Rp3rzEz4oKplw1tIJKCNBXhrdf+9l8bnf436A4H0JSzB84TUU64o6oZeGuB1ehpcoPXNe6XtdsDVEt908LYsH/7cEp88ZTbF92pWA8HOHnSt7Sy5JzBPiBZmFClC2R4ggOYHl7FRcRC+TSXX+x6HfSNIhD+21mIkZ6sQAW68EIQO6Q6lE6jzcxvmYLX4QcDgvWBfNwBNRHQdaZJCyw+R8nC8PIEVIDV3wn2np3aKf0mJCsCymkYfxMcMeK07RfFZ0nXw9If6sEWvKKyu0YulK81FLlS8oP86T96JSFwvVqrFkRCmAW+bSydZ8uc7sA5HQnNqB3MNxwN8+MaZ6QLhdo07u5FyP9N1awniHKSCpWUA2AYSfQG6XS36F6kb5K1tgd2DFUbBLBV4Iv+XgNMX3cJ6nfQ/L2baXdSrLR/FdEpDv+zcWYbG/kBj8w5rkMiRJncjcSOWbaSJ8M6V0JxeJPdE/QpXZ0rSUZKRk3FVXTxc="
